name: PlayerStatisticsPlugin
authors:
  - dehys
  - OverDodo
main: org.dreamndelight.playerstatistics.plugin.Main
version: 1.0.0
depend:
  - PlayerStatistics
load: STARTUP
database: true
api-version: 1.16

commands:
  stats:
    description: A simple stats command that displays some of the players statistics
    permission: playerstatistics.command.stats




permissions:
  playerstatistics.*:
    description: Grants all permissions for the PlayerStatistics-Plugin
    children:
      - playerstatistics.commands.*


  playerstatistics.command.*:
    description: Grants all command-based permissions for the PlayerStatistics-Plugin
    children:
      - playerstatistics.command.stats




  #Plain permissions
  playerstatistics.command.stats:
    description: Allows for the use of /stats