name: StatisticsLib
authors: [ dehys, OverDodo ]
version: '1.2.1_INDEV'
main: 'com.devflask.statisticslib.plugin.Plugin'
api-version: '1.16'
loadbefore:
  - PlayerStatisticsPlugin

commands:
  pslreload:
    permission: 'psl.reload'
    usage: '/pslreload'
    description: 'Reloads the PlayerStatisticsLib config.yml'
    executor: com.devflask.statisticslib.lib.command.ReloadCommand
